### ISSUE TITLE
No MSXX-XX field in update API

### ISSUE THREAD

**Issue by CaledoniaProject** [Microsoft/MSRC-Microsoft-Security-Updates-API#41]
The update API has some glitches but generally works. I can find KB id in it, but no MSXX-XX field in it, e.g MS17-023 

![screenshot 2019-02-16 at 12 07 20 am](https://user-images.githubusercontent.com/1357701/52868699-feae8000-317e-11e9-942a-d1e3853505ae.jpg)

Am I wrong?

**Comment by CaledoniaProject** [comment]
The old BulletinSearch excel has a MSXX-XX field, was it removed in the API?

**Comment by craig-martin** [comment]
Correct. The CVRF API only serves updates starting from when the API was released, it does not provide older items.  
How valuable is that scenario to you?

**Comment by craig-martin** [comment]
BTW I'd love to learn more about this:

> The update API has some glitches but generally works.

Can you provide detail (or create more issues) for the glitches?

**Comment by CaledoniaProject** [comment]
Hi @craig-martin, I didn't mean older data. 

For example, KB 4014329 can be found in `2017-Mar.json`, and the corresponding MS_ID is [ms17-023](https://docs.microsoft.com/en-us/security-updates/securitybulletins/2017/ms17-023), but it's not mentioned in `2017-Mar.json`.

**Comment by CaledoniaProject** [comment]
I have submitted issue for other glitches

**Comment by craig-martin** [comment]
Got it.  I'll get on those.

**Comment by craig-martin** [comment]
Regarding MS17-023, that is the older format called 'Security Bulletin', it is the last one in fact.  After that Microsoft switched to 'Security Updates', which is also when the CVRF API became available.  As far as I know we do not create KB articles for security updates anymore, we just link to them for the remediations in a vulnerability.

I think this is expected behavior, unless I'm not understanding the issue.

**Comment by CaledoniaProject** [comment]
Okay, understood. Closing this issue.
